version: "3"
  
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sonar_data
      PGDATA: /data/postgres
    volumes:
      - ./sonar-data:/data/postgres
    ports:
      - 5432:5432 
    networks:
      - env-network
  sonar:
    image: sonarqube
    container_name: sonar
    ports:
      - 9000:9000
      
networks:
  env-network:
    driver: bridge
